benchmarks:
- serenity_fuzzshell
- serenity_fuzzbmploader
description: null
docker_registry: gcr.io/fuzzbench
experiment: test3
experiment_filestore: /home/xgzhu/data/fuzzbench-data
fuzzers:
- aflchurn_seedalias_aco
- afl
git_hash: f74ccef7a9d709f01646fd03f881205d01e6da86
local_experiment: true
max_total_time: 900
no_dictionaries: false
no_seeds: false
oss_fuzz_corpus: false
report_filestore: /home/xgzhu/data/fuzzbench-reports
trials: 2
